data:
  type: shareGPT
load:
  type: constant
  stages:
  - rate: 1
    duration: 30
api: 
  type: chat
server:
  type: tgi
  model_name: HuggingFaceTB/SmolLM2-135M-Instruct
  base_url: http://0.0.0.0:8000
metrics:
  type: prometheus
  prometheus:
    url: http://localhost:9090
    scrape_interval: 15